#!/bin/bash
start=$(TZ='UTC+6:30' date +'%d/%m/%Y %H:%M:%S')

#initialize a working directory containing Terraform configuration files
terraform init

#create an execution plan
terraform plan -var-file=var_values.tfvars

#apply the changes generated by the execution plan
terraform apply -var-file=var_values.tfvars -auto-approve

end=$(TZ='UTC+6:30' date +'%d/%m/%Y %H:%M:%S')


echo Startdatetime $start
echo Enddatetime $end