- become: true
  hosts: all
  name: install apache mysql and PHP
  tasks:
    - name: install apache mysql and PHP
      ansible.builtin.yum:
       name: 
        - centos-release-scl
        - httpd24-httpd 
        - rh-php73 
        - rh-php73-php 
        - rh-php73-php-mbstring 
        - rh-php73-php-mysqlnd 
        - rh-php73-php-gd 
        - rh-php73-php-xml 
        - mariadb-server mariadb
       state: present

    - name: start mariadb
      become: true
      service:
        name: mariadb
        enabled: true
        state: started

    - name: create database
      become: true
      become_user: root  
      mysql_db: 
       name: wikidatabase
       state: present 

    - name: Create wiki user 
      become: true
      become_user: root       
      mysql_user:
         name: wiki
         password: Password
         priv: '*.*:ALL,GRANT'
         state: present 
    - name: Download the media wiki Tar
      get_url:
        url: 
          - "https://releases.wikimedia.org/mediawiki/1.38/mediawiki-1.38.2.tar.gz"
          - "https://releases.wikimedia.org/mediawiki/1.38/mediawiki-1.38.2.tar.gz.sig"
        dest: /home/mediawikivm 
    - name: Unzip the tar file
      become: true
      unarchive:
        src: /home/mediawikivm/mediawiki-1.38.2.tar.gz
        dest: /var/www
        remote_src: yes

    - name: Hardlink for MediaWiki
      become: true
      file :
        src: /home/mediawikivm/mediawiki-1.38.2
        dest: /home/mediawikivm/mediawiki
        state: link 

    - name: Update the Apache httpd conf file
      become: true
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'DocumentRoot \/var\/www'
        replace: 'DocumentRoot /var/www/mediawiki'    

     
    - name: Restart httpd
      become: true
      service:
        name: httpd
        state: Restart
        enabled: yes

    - name: Opening the firewall ports
      ansible.posix.firewalld:
      service:
        - https        
        - http
      permanent: yes
      zone: public

    - name: Restart firewalld
      become: true
      service:
        name: firewalld
        state: Restart
        enabled: yes  

    - name: Setting the correct selinux context
      ansible.built.command: 
       - restorecon -FR /var/www/mediawiki-1.38.2/ 
       - restorecon -FR /var/www/mediawiki  

    